### ISSUE TITLE
Incorrect dept. autoresponse email on the form

### ISSUE THREAD

**Issue by kopitoshka** [osTicket/osTicket-1.7#575] opened 2013-05-28 01:02 UTC
Hi,

I am using osticket 1.7.0 version. I have noticed a minor issue with selecting the active auto response email on the dept. form in admin area like this one:

http://www.examplecom/scp/departments.php?&id=1

There is a wrong comparison in the department.inc.php file. I hope it helps. 

Thank you.

**Comment by greezybacon** [comment] 2013-08-02 23:51
Thanks for the write up. I don't have access to your help desk. Could you post a screenshot?

**Comment by greezybacon** [comment] 2013-08-10 21:15
@kopitoshka, I can't reproduce this. Can you explain the bug in more detail or post some screenshots?

**Comment by kopitoshka** [comment] 2013-08-10 21:28
Sorry for the delay in my response. Could you please check the line (195) in the file (/include/staff /department.inc.php):
$selected=($info['email_id'] && $id==$info['email_id'])?'selected="selected"':'';

I believe it should look like this:
$selected=($info['email_id'] && $id==$info['autoresp_email_id'])?'selected="selected"':'';

I made these changes to a copy of my osticket 1.7.0 and it works fine.

**Comment by greezybacon** [comment] 2013-08-11 04:41
Thanks for pointing this out. It's fixed in the [release](https://github.com/osTicket/osTicket-1.7/tree/release) branch and **will** be included in the 1.7.1 release this week.

**Closed as completed** 2013-08-11 05:25 UTC
Labels: bug, fix-available
