### ISSUE TITLE
Ticket printing issue and attachments not storing/opening correctly

### ISSUE THREAD

**Issue by josh1856** [osTicket/osTicket-1.7#579] opened 2013-06-03 22:30 UTC
After updating to the latest version via pull.  Started receiving random errors:
- When in a ticket and click the print function receiving the following error:  FPDF error: Some data has already been output, can't send PDF file
- When SOME attached files more specifically .xls, .jpg, .docx come into the system via fetch or web creation they are stored or delivered in corrupted format.  PDF files and .pptx seem to work fine.

**Comment by josh1856** [comment] 2013-06-03 22:39
Here are some examples
![doc_test](https://f.cloud.github.com/assets/2126322/602524/62029e8a-cc9e-11e2-9bd0-2024755ca398.jpg)
![xls_test](https://f.cloud.github.com/assets/2126322/602525/685385ec-cc9e-11e2-9c86-438038d151b9.jpg)
![ticket_print](https://f.cloud.github.com/assets/2126322/602526/6cbb487c-cc9e-11e2-99d0-6a32d0a72d65.jpg)

**Comment by josh1856** [comment] 2013-06-03 23:10
I was able to solve the printing ticket issue by cleaning the headers by adding the following to class.pdf.php after line 51.  Would someone please verify the code and add if necessary.

50        //report header...most stuff are hard coded for now...
51       function Header() {
52       while (ob_get_level())
53       ob_end_clean();
54       header("Content-Encoding: None", true);
55       global $cfg;

**Comment by FourFoot** [comment] 2013-06-05 11:47
Just following this, but we're seeing a corruption issue on all attachments coming through email pipe. Tested with .docx, .pdf, .jpg, .png, .psd, .xlsx file sizes ranging from 10KB through to 22MB

**Comment by josh1856** [comment] 2013-06-05 14:01
I have confirmed .zip files as well.  I also tried a number of sizes and it does not seem to matter what size the document is it corrupts the document.  Although I am able to get ALL sized pdf files to work.

**Comment by FourFoot** [comment] 2013-06-05 14:47
Seems to be fine if we retrieve the emails via POP3. We've experienced attachment corruption issues on other software when the email was piped directly to it (it added odd characters to the end of the file, which is what we're seeing in the file chunks OsTicket creates), turned out to be due to the MIME encoding of the email/attachment, might be similar problem here...

**Comment by greezybacon** [comment] 2013-06-05 18:31
How did you guys come across this issue? Is this a streamed (git tracking) upgrade or a fresh install?

I'm just wondering where I should go and start looking for culprits?

**Comment by josh1856** [comment] 2013-06-05 18:32
My issue came up when I did a gitpul upgrade.  Prior to the last update everything worked flawless.

**Comment by FourFoot** [comment] 2013-06-05 18:57
I found this attachment corruption on piped emails issue on a fresh 1.7.0 install from osticket.com an update from github about 6hrs ago didn't change it.

**Comment by josh1856** [comment] 2013-06-05 19:01
I am able to replicate this issue via regardless of pull/creation method IMAP/POP3 or uploading to the public portal directly.  So it must have something to do with FILE CHUNKS!

**Comment by josh1856** [comment] 2013-06-05 23:51
I just did a fresh install and was able to replicate the issue also.  Greezybacon were you able to replicate?  Fourfoot what version of MySQL re you using?

**Comment by FourFoot** [comment] 2013-06-06 08:13
MySQL version is 5.1.69-cll. However, for me on the fresh install uploads via the /scp/ panel are fine, and emailed via POP3 are fine - just when they're directly piped that's causing me an issue. Using the same files for testing each time. Are you experiencing the issue with ALL methods on the fresh install?

**Comment by josh1856** [comment] 2013-06-06 12:01
It is happening on all methods with mine on upgrade and fresh install.  I also tested it on a backup of a fully working version and then upgraded.  Tickets that were created prior to the upgrade open properly and once the upgrade is completed the previously created/closed ticket attachments no longer open attachments properly.  All previous PDF files open correctly.  Errors are still created opening .xls, .tiff, .jpg, .png.  Perhaps the issue lies in the pull/fetch request?

**Comment by josh1856** [comment] 2013-06-06 14:44
I am on MySQL 5.0.77

**Comment by josh1856** [comment] 2013-06-07 02:03
Greezybacon did you replicate?

**Comment by greezybacon** [comment] 2013-06-07 16:11
Josh, honestly I haven't had time to review it yet. My hunch is that the problem is in the http response code rather than the database fetch code

**Comment by josh1856** [comment] 2013-06-09 16:13
Greezybacon did you change the http response code in Ny recent updates?

**Comment by greezybacon** [comment] 2013-06-13 14:14
I believe this is fixed in #583, can someone verify

**Comment by josh1856** [comment] 2013-06-13 18:59
Confirmed fixed.

**Comment by greezybacon** [comment] 2013-06-13 21:44
@josh1856, the fix is merged, and I added a test to find leading and trailing whitespace in the code in hopes of avoiding this issue again in the future.

**Comment by josh1856** [comment] 2013-06-26 04:14
Glad we got it fixed and I could help.  Did you commit the print issue?

**Comment by greezybacon** [comment] 2013-06-26 18:14
#536 is a different issue. The email address does not fit in the space given on the PDF output

**Closed as completed by greezybacon** 2013-06-26 18:14 UTC
Labels: bug
