### ISSUE TITLE
table "ost_ticket_thread" -> field "title" has wrong encoding

### ISSUE THREAD

**Issue by PawelBaczkiewicz** [osTicket/osTicket-1.7#718] opened 2013-09-12 19:31 UTC
Hi,

Since I've upgraded my osticket version I noticed field "title" is incorrectly encoded in table "ost_ticket_thread".
Value is also displayed incorrectly.

Example in Polish language: "wówczas".

"ó" is translated into: &oacute;. This value is also displayed in osticket threads in staff panel. If you create a ticket putting "Subject" as "wówczas", the ticket is created with correct title "wówczas", but thread title is converted into "w&oacute;wczas".

Would be nice to have fix that.

**Comment by greezybacon** [comment] 2013-09-13 14:29
Thanks for bringing this up again. It's a duplicate of #567. I agree it needs to be addressed pronto

**Comment by PawelBaczkiewicz** [comment] 2013-09-13 14:56
Sorry for duplicating :/ I hope it will be fixed soon.
Thanks in advance.

**Comment by greezybacon** [comment] 2013-09-13 15:17
I've mocked it up in #720. I would appreciate your feedback if it correctly addresses the issue

**Comment by greezybacon** [comment] 2013-09-24 22:33
Thanks for reporting this! It was merged and released into 1.7.1.3

**Closed as completed by greezybacon** 2013-09-24 22:33 UTC
Labels: duplicate
